server.port=8082
spring.application.name=ms-gestion-alumno

# Base de Datos
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/bd_alumno
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT (debe coincidir con el Gateway)
jwt.secret=claveSuperSecretaParaJWT2024MicroserviciosGestionAcademicaChavez
jwt.expiration=86400000
