server.port=8083
spring.application.name=ms-gestion-taller

# Base de Datos
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/bd_taller
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT (debe coincidir con el Gateway)
jwt.secret=claveSuperSecretaParaJWT2024MicroserviciosGestionAcademicaChavez
jwt.expiration=86400000

# Feign Circuit Breaker
spring.cloud.openfeign.circuitbreaker.enabled=true

# Feign Timeouts
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.ms-gestion-instructor.slidingWindowSize=5
resilience4j.circuitbreaker.instances.ms-gestion-instructor.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.ms-gestion-instructor.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ms-gestion-instructor.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.ms-gestion-instructor.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.instances.ms-gestion-alumno.slidingWindowSize=5
resilience4j.circuitbreaker.instances.ms-gestion-alumno.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.ms-gestion-alumno.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ms-gestion-alumno.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.ms-gestion-alumno.permittedNumberOfCallsInHalfOpenState=2
