server.port=8083
spring.application.name=ms-gestion-taller

# Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_taller
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT (debe coincidir con el Gateway)
jwt.secret=claveSuperSecretaParaJWT2024MicroserviciosGestionAcademicaChavez
jwt.expiration=86400000

# Feign Circuit Breaker
spring.cloud.openfeign.circuitbreaker.enabled=true

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.instructorService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.instructorService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.instructorService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.instructorService.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.instructorService.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.instances.alumnoService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.alumnoService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.alumnoService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.alumnoService.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.alumnoService.permittedNumberOfCallsInHalfOpenState=2
